### ISSUE TITLE
DMR Layer 1

### ISSUE THREAD

**Issue by alwinhb** [DVMProject/dvmfirmware#5]
@gatekeep @k4yt3x @W3AXL  

Does this source code contain complete layer 1, Implementation? 

I want to use the code only for DMR, I want to remove nxdn and p25 does it work?

**Comment by alwinhb** [comment]
@gatekeep Can you advice on above

**Comment by gatekeep** [comment]
If you mean for *just* modulation, in theory yes. But using this code alone is essentially worthless, as it will only get you the DMR modulation, and nothing else. The firmware code contains the lowest level of modulation/demodulation and CACH handling, and that is it.

**Comment by alwinhb** [comment]
@gatekeep Thanks, Ill try to use this one for modulation, Meanwhile can you share more relevant code references for DMR [PHY, DATA LINK and CONTROL LAYER] if you have ever came across any!
